# Utiliser l'image de base PHP avec FPM
FROM php:8.2-fpm

# Installer des dépendances système nécessaires pour Symfony
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpq-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql zip opcache

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Définir le répertoire de travail
WORKDIR /var/www/symfony

# Copier les fichiers de l'application Symfony
COPY . /var/www/symfony

# Exposer le port de PHP-FPM
EXPOSE 9000
